import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { IonicModule } from '@ionic/angular';
import {
  IonAccordion,
  IonAccordionGroup,
  IonItem,
  IonLabel,
  IonChip,
  IonPicker,
  IonPickerColumn,
  IonPickerColumnOption,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonInput,
  IonList,
  IonContent,
  IonButton,
  IonHeader,
  IonMenu,
  IonTitle,
  IonToolbar,
  IonSelect,
  IonSelectOption,
  IonRange
} from '@ionic/angular/standalone';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    IonAccordion,
    IonAccordionGroup,
    IonItem,
    IonLabel,
    IonChip,
    IonPicker,
    IonPickerColumn,
    IonPickerColumnOption,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonButton,
    IonCardSubtitle,
    IonCardTitle,
    IonInput,
    IonList,
    IonContent,
    IonHeader,
    IonMenu,
    IonTitle,
    IonToolbar,
    IonSelect,
    IonSelectOption,IonRange
  ],
  exports: [
    CommonModule,
    FormsModule,
    IonicModule,
    IonAccordion,
    IonAccordionGroup,
    IonItem,
    IonLabel,
    IonChip,
    IonPicker,
    IonPickerColumn,
    IonPickerColumnOption,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonInput,
    IonList,
    IonButton,
    IonContent,
    IonHeader,
    IonMenu,
    IonTitle,
    IonToolbar,
    IonItem,
    IonList,
    IonSelect,
    IonSelectOption,
    IonSelect,
    IonSelectOption,IonRange
  ],
})
export class SharedModule {}
